"""Endpoints para gestión de outreach (emails, seguimiento)."""
from __future__ import annotations

import uuid
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import get_settings
from app.core.database import get_session
from app.models.lead import Lead
from app.models.sales_intelligence import SalesIntelligence
from app.schemas.outreach import OutreachCreate, OutreachListResponse, OutreachRead, OutreachUpdate
from app.services.email_service import EmailConfig, EmailService
from app.services.lead_service import LeadService
from app.services.outreach_service import OutreachService

router = APIRouter(prefix="/outreach", tags=["outreach"])


@router.post("", response_model=OutreachRead, status_code=201)
async def create_outreach(
    payload: OutreachCreate,
    session: AsyncSession = Depends(get_session),
):
    service = OutreachService(session)
    msg = await service.create(payload)
    return OutreachRead.model_validate(msg)


@router.get("", response_model=OutreachListResponse)
async def list_outreach(
    lead_id: Optional[uuid.UUID] = Query(default=None),
    limit: int = Query(default=50, ge=1, le=200),
    offset: int = Query(default=0, ge=0),
    session: AsyncSession = Depends(get_session),
):
    service = OutreachService(session)
    items, total = await service.list(lead_id=lead_id, limit=limit, offset=offset)
    return OutreachListResponse(
        items=[OutreachRead.model_validate(i) for i in items],
        total=total,
        limit=limit,
        offset=offset,
    )


@router.get("/{msg_id}", response_model=OutreachRead)
async def get_outreach(
    msg_id: uuid.UUID,
    session: AsyncSession = Depends(get_session),
):
    service = OutreachService(session)
    msg = await service.get(msg_id)
    if msg is None:
        raise HTTPException(status_code=404, detail="Outreach message not found")
    return OutreachRead.model_validate(msg)


@router.patch("/{msg_id}", response_model=OutreachRead)
async def update_outreach(
    msg_id: uuid.UUID,
    payload: OutreachUpdate,
    session: AsyncSession = Depends(get_session),
):
    service = OutreachService(session)
    msg = await service.update(msg_id, payload)
    if msg is None:
        raise HTTPException(status_code=404, detail="Outreach message not found")
    return OutreachRead.model_validate(msg)


@router.post("/{msg_id}/track-open")
async def track_open(msg_id: uuid.UUID, session: AsyncSession = Depends(get_session)):
    service = OutreachService(session)
    await service.track_open(msg_id)
    return {"status": "tracked"}


@router.post("/{msg_id}/track-click")
async def track_click(msg_id: uuid.UUID, session: AsyncSession = Depends(get_session)):
    service = OutreachService(session)
    await service.track_click(msg_id)
    return {"status": "tracked"}


@router.post("/{msg_id}/track-reply")
async def track_reply(msg_id: uuid.UUID, session: AsyncSession = Depends(get_session)):
    service = OutreachService(session)
    await service.track_reply(msg_id)
    return {"status": "tracked"}


@router.post("/send")
async def send_outreach_email(
    lead_id: uuid.UUID = Query(...),
    subject: Optional[str] = Query(default=None),
    body: Optional[str] = Query(default=None),
    session: AsyncSession = Depends(get_session),
):
    """Send the cold email generated by the Closer to the lead.

    Optionally override the subject and body before sending.
    """
    settings = get_settings()

    # Get lead
    result = await session.execute(select(Lead).where(Lead.id == lead_id))
    lead = result.scalar_one_or_none()
    if not lead:
        raise HTTPException(status_code=404, detail="Lead not found")

    # Get latest sales intelligence
    result = await session.execute(
        select(SalesIntelligence)
        .where(SalesIntelligence.lead_id == lead_id)
        .order_by(SalesIntelligence.generated_at.desc())
        .limit(1)
    )
    intel = result.scalar_one_or_none()
    if not intel:
        raise HTTPException(
            status_code=400,
            detail="No sales intelligence available. Run the Closer first.",
        )

    # Get recipient email
    recipient = lead.email
    if not recipient:
        # Try latest audit extracted contacts
        from app.models.audit import Audit
        result = await session.execute(
            select(Audit)
            .where(Audit.lead_id == lead_id)
            .order_by(Audit.created_at.desc())
            .limit(1)
        )
        latest_audit = result.scalar_one_or_none()
        if latest_audit:
            contacts = latest_audit.extracted_contacts or {}
            emails = contacts.get("emails", [])
            if emails:
                recipient = emails[0]

    if not recipient:
        raise HTTPException(status_code=400, detail="No email address found for this lead.")

    # Use overrides if provided, otherwise fall back to generated intel
    final_subject = subject or intel.cold_email_subject or "Propuesta de mejora para su sitio web"
    final_body = body or intel.cold_email_body or ""

    # Append sender signature if available
    from app.services.sender_profile_service import SenderProfileService
    profile_service = SenderProfileService(session)
    sender_profile = await profile_service.get_active()
    if sender_profile and sender_profile.email_signature:
        if sender_profile.email_signature not in final_body:
            final_body = final_body.rstrip() + "\n\n" + sender_profile.email_signature

    # Send email
    email_service = EmailService(
        EmailConfig(
            provider=getattr(settings, "email_provider", "resend"),
            api_key=getattr(settings, "email_api_key", ""),
            from_email=getattr(settings, "email_from", "outreach@siphonx.dev"),
            from_name=getattr(settings, "email_from_name", "SIPHON-X Outreach"),
        )
    )

    result = await email_service.send(
        to=recipient,
        subject=final_subject,
        body=final_body,
    )

    if result.success:
        # Record the outreach message
        outreach_service = OutreachService(session)
        msg = await outreach_service.create(
            OutreachCreate(
                lead_id=str(lead_id),
                sales_intel_id=str(intel.id),
                channel="email",
                recipient=recipient,
                subject=final_subject,
                body=final_body,
                provider_message_id=result.message_id,
            )
        )

        # Update lead status
        from app.models.lead import LeadStatus

        lead_service = LeadService(session)
        await lead_service.transition_status(lead_id, LeadStatus.contacted)

        return {
            "status": "sent",
            "message_id": result.message_id,
            "outreach_id": str(msg.id),
            "recipient": recipient,
        }
    else:
        raise HTTPException(status_code=500, detail=f"Failed to send email: {result.error}")
